[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of Transfers in the SAFE Network."
documentation = "https://docs.rs/safe-transfers"
edition = "2018"
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
name = "safe-transfers"
readme = "README.md"
repository = "https://github.com/maidsafe/safe-transfers"
version = "0.1.0"

[dependencies]
# # Ensure bincode version is identical to that in SAFE Client Libs and SAFE Network Data.
bincode = "1.2.1"
safe-nd = { git = "https://github.com/maidsafe/safe-nd", branch = "at2" }
# safe-nd = { git ="https://github.com/yoga07/safe-nd", branch="at2", features=["simulated-payouts"] }
# safe-nd = { path="../safe-nd" }
serde = { version = "1.0.97", features = ["derive"] }
crdts = "4.1.0"
threshold_crypto = "~0.3.2"
rand = "~0.6.5"
itertools = "~0.9.0"

[dev_dependencies]

[features]
simulated-payouts = ["safe-nd/simulated-payouts"]