[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "Implementation of Transfers in the SAFE Network."
documentation = "https://docs.rs/safe-transfers"
edition = "2018"
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
name = "safe-transfers"
readme = "README.md"
repository = "https://github.com/maidsafe/safe-transfers"
version = "0.1.0"

# [patch.crates-io]
# safe-nd =  { git = "https://github.com/oetyng/safe-nd.git", rev = "2c16b8c" }

[dependencies]
# # Ensure bincode version is identical to that in SAFE Client Libs and SAFE Network Data.
bincode = "=1.1.4"
safe-nd = { git = "https://github.com/oetyng/safe-nd.git", branch = "at2-network-payments" }
serde = { version = "~1.0.97", features = ["derive"] }
crdts = { git = "https://github.com/rust-crdt/rust-crdt", branch = "useability-improvements" }
threshold_crypto = "~0.3.2"
rand = "~0.6.5"

[dev_dependencies]